// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Payment struct {
	ID             uuid.UUID          `json:"id"`
	Amount         decimal.Decimal    `json:"amount"`
	Currency       string             `json:"currency"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
