// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*) as total
FROM payments
`

func (q *Queries) CountPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentsByStatus = `-- name: CountPaymentsByStatus :one
SELECT COUNT(*) as total
FROM payments
WHERE status = $1
`

func (q *Queries) CountPaymentsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByStatus, status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, amount, currency, idempotency_key, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, amount, currency, idempotency_key, status, created_at, processed_at, updated_at
`

type CreatePaymentParams struct {
	ID             uuid.UUID          `json:"id"`
	Amount         decimal.Decimal    `json:"amount"`
	Currency       string             `json:"currency"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (*Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.IdempotencyKey,
		arg.Status,
		arg.CreatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, amount, currency, idempotency_key, status, created_at, processed_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (*Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaymentByIDForUpdate = `-- name: GetPaymentByIDForUpdate :one
SELECT id, amount, currency, idempotency_key, status, created_at, processed_at, updated_at
FROM payments
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPaymentByIDForUpdate(ctx context.Context, id uuid.UUID) (*Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIDForUpdate, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, amount, currency, idempotency_key, status, created_at, processed_at, updated_at
FROM payments
WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (*Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaymentsByStatus = `-- name: GetPaymentsByStatus :many
SELECT id, amount, currency, idempotency_key, status, created_at, processed_at, updated_at
FROM payments
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetPaymentsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetPaymentsByStatus(ctx context.Context, arg GetPaymentsByStatusParams) ([]*Payment, error) {
	rows, err := q.db.Query(ctx, getPaymentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.IdempotencyKey,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, amount, currency, idempotency_key, status, created_at, processed_at, updated_at
FROM payments
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]*Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.IdempotencyKey,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = $2, processed_at = $3, updated_at = NOW()
WHERE id = $1 AND status = $4
`

type UpdatePaymentStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	Status_2    string             `json:"status_2"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.ProcessedAt,
		arg.Status_2,
	)
	return err
}
